name: CD

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name'
        required: true


permissions:
  contents: write # VERY IMPORTANT: This is required for the component-detection-dependency-submission-action to work, otherwise it will silently fail
  id-token: write # VERY IMPORTANT: This is required for the component-detection-dependency-submission-action to work, otherwise it will silently fail

jobs:
  on_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download release asset
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download -R "${{ github.repository }}" "${{ inputs.release_name }}" -p "artifact.zip"

          unzip artifact.zip -d .

      - name: SBOM upload 
        uses: advanced-security/spdx-dependency-submission-action@v0.1.1
        with:
          filePattern: "sbom-spdx2_2_enriched.json"
