name: Dotnet sbomtool 

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        uses: ./.github/actions/tools

      - name: Generate SBOM
        working-directory: dotnet
        run: |
          dotnet publish Application/Application.csproj --configuration Release --output publish

          dotnet tool install --global Microsoft.Sbom.DotNetTool
          sbom-tool generate -bc . -b ./publish -pn Application -pv 1.0.0 -ps DataHub -li true -V Verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4 
        with:
          name: artifact
          path: dotnet/publish

      - name: Create release
        uses: ./.github/actions/create-release
        with:
          directory: dotnet/publish
          release_name: "dotnet_sbomtool"
          github_token: ${{ secrets.GITHUB_TOKEN }}
