name: Dotnet trivy 

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - dotnet/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        uses: ./.github/actions/tools

      - name: Generate SBOM
        working-directory: dotnet
        run: |
          dotnet publish Application/Application.csproj --configuration Release --output publish

          trivy fs --format spdx-json --output publish/sbom-spdx2_2.json Application
          cat publish/sbom-spdx2_2.json | parlay ecosystems enrich - | jq . > publish/sbom-spdx2_2_enriched.json

          trivy fs --format cyclonedx --output publish/sbom-cyclonedx.json Application
          cat publish/sbom-cyclonedx.json | parlay ecosystems enrich - | jq . > publish/sbom-cyclonedx1_6_enriched.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4 
        with:
          name: artifact
          path: dotnet/publish

      - name: Create release
        uses: ./.github/actions/create-release
        with:
          directory: dotnet/publish
          release_name: "dotnet_trivy"
          github_token: ${{ secrets.GITHUB_TOKEN }}
