name: Python trivy 

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - python/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        uses: ./.github/actions/tools

      - name: Generate SBOM
        working-directory: python
        run: |
          # uv sync creates a virtual environment and installs dependencies which is required for SBOM generation
          uv sync
          
          trivy fs --format spdx-json --output sbom-spdx2_2.json --include-dev-deps .
          cat sbom-spdx2_2.json | parlay ecosystems enrich - | jq . > sbom-spdx2_2_enriched.json

          trivy fs --format cyclonedx --output sbom-cyclonedx.json --include-dev-deps .
          cat sbom-cyclonedx.json | parlay ecosystems enrich - | jq . > sbom-cyclonedx1_6_enriched.json

          uv build --wheel --out-dir publish

          cp sbom-spdx2_2.json publish/sbom-spdx2_2.json
          cp sbom-spdx2_2_enriched.json publish/sbom-spdx2_2_enriched.json
          
          cp sbom-cyclonedx.json publish/sbom-cyclonedx.json
          cp sbom-cyclonedx1_6_enriched.json publish/sbom-cyclonedx1_6_enriched.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4 
        with:
          name: artifact
          path: python/publish

      - name: Create release
        uses: ./.github/actions/create-release
        with:
          directory: python/publish
          release_name: "python_trivy"
          github_token: ${{ secrets.GITHUB_TOKEN }}
