name: Python syft 

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        uses: ./.github/actions/tools

      - name: Generate SBOM
        working-directory: python
        run: |
          # uv sync creates a virtual environment and installs dependencies which is required for SBOM generation
          uv sync
          
          syft . -o spdx-json | jq . > sbom-spdx2_3.json
          cat sbom-spdx2_3.json | parlay ecosystems enrich - | jq . > sbom-spdx2_3_enriched.json

          syft . -o cyclonedx-json | jq . > sbom-cyclonedx1_6.json
          cat sbom-cyclonedx1_6.json | parlay ecosystems enrich - | jq . > sbom-cyclonedx1_6_enriched.json

          uv build --wheel --out-dir publish
          cp sbom-spdx2_3.json publish/sbom-spdx2_3.json
          cp sbom-spdx2_3_enriched.json publish/sbom-spdx2_3_enriched.json
          cp sbom-cyclonedx1_6.json publish/sbom-cyclonedx1_6.json
          cp sbom-cyclonedx1_6_enriched.json publish/sbom-cyclonedx1_6_enriched.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4 
        with:
          name: artifact
          path: python/publish

      - name: Create release
        uses: ./.github/actions/create-release
        with:
          directory: python/publish
          release_name: "python_syft"
          github_token: ${{ secrets.GITHUB_TOKEN }}
