name: On release

on:
  release:
    types: [published]

permissions:
  # contents: write # VERY IMPORTANT: This is required for the component-detection-dependency-submission-action to work, otherwise it will silently fail
  # id-token: write # VERY IMPORTANT: This is required for the component-detection-dependency-submission-action to work, otherwise it will silently fail

jobs:
  on_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download release asset
        shell: bash
        run: |
          gh release download -R "${{ github.repository }}" "${{ github.ref }}" -p "artifact.zip"
